In [6]:
import numpy as np
from scipy.linalg import *

In [14]:
#### Problem 1 #####
A = np.array([[1,2,3],[4,5,6]])
print(A)
print("The size of A is: "+str(np.shape(A)))
print(A.T)
print("The size of A transpose is: "+str(np.shape(A.T)))

[[1 2 3]
 [4 5 6]]
The size of A is: (2, 3)
[[1 4]
 [2 5]
 [3 6]]
The size of A transpose is: (3, 2)


In [59]:
#### Problem 2 ####

#Given Matrices
A=np.array([[5,3],[1,2]])
B=np.array([[1,2],[5,6]])
C=np.array([[11,5],[5,4]])

#Calculated Matrices
D1=A@(B+C)
D2=A@B+A@C

print(D1)
print("")
print(D2)


A@C


[[90 65]
 [32 27]]

[[90 65]
 [32 27]]


array([[70, 37],
       [21, 13]])

In [55]:
#### Problem 3 ####
def dfdq(q1,q2,q3,t):
    dq=np.array([q3,-6*q2,q1])
    return dq;

def dfdt(q1,q2,q3,t):
    df=dfdq(q1,q2,q3,t)
    dfdt = np.dot(df,[2, 5, 2*t])+10*t
    return dfdt;

####Testing the function
t = 2;
q1=2*t;
q2=5*t;
q3=t**2;
print("Hand-Derived Result: dfdt = "+str(t*(6*t-140)))
print("Numerical Result:    dfdt = "+str(dfdt(q1,q2,q3,t)))

Hand-Derived Result: dfdt = -256
Numerical Result:    dfdt = -256


In [56]:
#### Problem 4 ####
def dfdq2(q,t):
    '''Here q=[q1,q2,q3] and t = time'''
    df = np.array([[2*q[0],6*q[1],-15*q[2]**2],[0,2*q[1],-2*q[2]],[q[2],q[2],q[0]+q[1]]])
    return df

q=np.array([1,3,5])
t=3
dfdq2(q,t)

array([[   2,   18, -375],
       [   0,    6,  -10],
       [   5,    5,    4]])

In [52]:
#### Problem 5 ####
A=np.array([[-3,8,-20.5],[5,11,13],[7,20,0]])
B=np.array([[0,3.2,0],[-17.5,5.7,0],[12,6.8,-10]])

#Sum of A,B
C = A+B;
print("The sum of A and B is: ");print(C);print("")

#Determinants of A,B, and A+B
print("The determinant of A is:   det(A) = "+str(np.linalg.det(A)))
print("The determinant of B is:   det(B) = "+str(np.linalg.det(B)))
print("The determinant of A+B is: det(A+B) = "+str(np.linalg.det(C)))
print("")

#Trace (Sum of Diagonal Elements) of A,B, and A+B
print("The trace of A is:          trace(A) = "+str(np.trace(A)))
print("The trace of B is:          trace(B) = "+str(np.trace(B)))
print("The trace of A+B is:        trace(A+B) = "+str(np.trace(C)))
print("")


The sum of A and B is: 
[[ -3.   11.2 -20.5]
 [-12.5  16.7  13. ]
 [ 19.   26.8 -10. ]]

The determinant of A is:   det(A) = 1036.4999999999995
The determinant of B is:   det(B) = -560.0000000000003
The determinant of A+B is: det(A+B) = 16284.749999999976

The trace of A is:          trace(A) = 8.0
The trace of B is:          trace(B) = -4.3
The trace of A+B is:        trace(A+B) = 3.6999999999999993

